# Generated by Django 5.2.17 on 2026-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='city_state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
