# Generated by Django 5.2.17 on 2026-08-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_useractivitylog_city_state_useractivitylog_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='city_state',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user_id',
        ),
    ]
