# Generated by Django 5.2.17 on 2026-08-18 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_state_slugs(apps, schema_editor):
    State = apps.get_model("dashboard", "State")

    for state in State.objects.all():
        base_slug = slugify(state.name) or f"state-{state.id}"

        slug = base_slug
        counter = 2

        while State.objects.filter(slug=slug).exclude(pk=state.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        state.slug = slug
        state.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0006_adminsetting_aigeneration_chatsession_notification_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aigeneration",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="chatbotlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["ranking"]},
        ),
        migrations.AlterModelOptions(
            name="generatedimage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="profitloss",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="useractivitylog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="wallpaper",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RenameField(
            model_name="profitloss",
            old_name="expenses",
            new_name="expense",
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="adminsetting",
            name="key",
        ),
        migrations.RemoveField(
            model_name="adminsetting",
            name="value",
        ),
        migrations.RemoveField(
            model_name="aigeneration",
            name="username",
        ),
        migrations.RemoveField(
            model_name="chatbotlog",
            name="bot_response",
        ),
        migrations.RemoveField(
            model_name="chatbotlog",
            name="user_message",
        ),
        migrations.RemoveField(
            model_name="chatbotlog",
            name="username",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="username",
        ),
        migrations.RemoveField(
            model_name="country",
            name="name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="username",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="wallpaper",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="profitloss",
            name="title",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="area",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
        migrations.AddField(
            model_name="adminsetting",
            name="setting_name",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name="adminsetting",
            name="setting_value",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="aigeneration",
            name="user",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="chatbotlog",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatbotlog",
            name="response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatbotlog",
            name="user",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="city",
            name="areas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="city",
            name="coordinates",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="dashboard.country",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="tile_hub",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="continent",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="country",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="country",
            name="country_type",
            field=models.CharField(
                choices=[
                    ("Producer", "Producer"),
                    ("Consumer", "Consumer"),
                    ("Producer, Consumer", "Producer, Consumer"),
                ],
                default="Consumer",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="products",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="country",
            name="ranking",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="user",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="profitloss",
            name="profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
            ),
        ),

        # Add slug without unique constraint first.
        migrations.AddField(
            model_name="state",
            name="slug",
            field=models.SlugField(
                default="",
                max_length=120,
            ),
        ),

        # Populate unique slugs for existing State records.
        migrations.RunPython(
            populate_state_slugs,
            migrations.RunPython.noop,
        ),

        migrations.AddField(
            model_name="userprofile",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="aigeneration",
            name="model",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="aigeneration",
            name="negative_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="aigeneration",
            name="prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="session_id",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="dashboard.state",
            ),
        ),
        migrations.AlterField(
            model_name="generatedimage",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="dashboard.aigeneration",
            ),
        ),
        migrations.AlterField(
            model_name="generatedimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="generated_images/",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default="",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                    ("Refunded", "Refunded"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="profitloss",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="state",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="dashboard.country",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="username",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.category",
            ),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="wallpapers/",
            ),
        ),
        migrations.AlterField(
            model_name="wallpaper",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.CreateModel(
            name="AreaVillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("Area", "Area"),
                            ("Village", "Village"),
                        ],
                        default="Area",
                        max_length=20,
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "showrooms",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_villages",
                        to="dashboard.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_villages",
                        to="dashboard.country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_villages",
                        to="dashboard.state",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PermissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(default=False),
                ),
                (
                    "can_manage_wallpapers",
                    models.BooleanField(default=False),
                ),
                (
                    "can_manage_ai",
                    models.BooleanField(default=False),
                ),
                (
                    "can_manage_orders",
                    models.BooleanField(default=False),
                ),
                (
                    "can_view_analytics",
                    models.BooleanField(default=False),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Area",
        ),
    ]