# Generated by Django 5.2.17 on 2026-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_aigeneration_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
    ]
