# Generated by Django 5.2.17 on 2026-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_state_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='generation_type',
            field=models.CharField(choices=[('Mural', 'AI Wall Mural'), ('Kids', 'AI Kids'), ('Painting', 'AI Painting'), ('Wall Art', 'AI Wall Art'), ('Texture', 'AI Texture'), ('3D Mural', 'AI 3D Mural'), ('Ceiling', 'AI Ceiling')], default='Mural', max_length=50),
        ),
    ]
