# Generated by Django 5.2.17 on 2026-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_aigeneration_generation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWallpaperGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=150)),
                ('style', models.CharField(choices=[('AI Painting', 'AI Painting'), ('AI Wall Mural', 'AI Wall Mural'), ('AI Wallpaper Roll', 'AI Wallpaper Roll'), ('AI Wall Art', 'AI Wall Art'), ('AI Texture', 'AI Texture'), ('AI Kids & Nursery', 'AI Kids & Nursery'), ('AI 3D Mural', 'AI 3D Mural'), ('AI Ceiling Art', 'AI Ceiling Art')], default='AI Painting', max_length=100)),
                ('prompt', models.TextField(blank=True, default='')),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('aspect_ratio', models.CharField(choices=[('Square', 'Square'), ('Landscape', 'Landscape'), ('Portrait', 'Portrait')], default='Square', max_length=30)),
                ('model_used', models.CharField(blank=True, default='Stable Diffusion XL', max_length=150)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated_wallpapers/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Wallpaper Generator',
                'verbose_name_plural': 'AI Wallpaper Generators',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='generation',
        ),
        migrations.DeleteModel(
            name='AIGeneration',
        ),
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
