# Generated by Django 5.2.17 on 2026-08-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_aiwallpapergenerator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=150)),
                ('prompt', models.TextField(blank=True, default='')),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.aigeneration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIWallpaperGenerator',
        ),
    ]
