# Generated by Django 5.2.17 on 2026-08-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_aigeneration_generatedimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWallpaperStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='generation',
        ),
        migrations.CreateModel(
            name='AIWallpaperGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=150)),
                ('prompt', models.TextField(blank=True, default='')),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('aspect_ratio', models.CharField(choices=[('Square', 'Square'), ('Landscape', 'Landscape'), ('Portrait', 'Portrait')], default='Square', max_length=20)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='ai_wallpapers/')),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='dashboard.aiwallpaperstyle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIGeneration',
        ),
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
